### ISSUE TITLE
在新的微信8.0.48版本失效了……

### ISSUE THREAD

**Issue by xairt** [rarnu/WeChatPad#4]
嵌入之后，只能出现仅平板使用，同时在手机和平板上使用的选项无法出现

**Comment by knowanegg** [comment]
今天刚开始用，发现就失效了。。。哪个大佬给个能用的微信版本号？

**Comment by xairt** [comment]
> 今天刚开始用，发现就失效了。。。哪个大佬给个能用的微信版本号？

上一个版本8.0.47就可以

**Comment by yangloft** [comment]
附议，微信8.0.48版本失效了；
临时方案：在47版平板模式登录后，然后升级48可以保留登录，注意备份聊天数据

**Comment by androidcn** [comment]
8.0.48确实失效了

**Comment by androidcn** [comment]
> 附议，微信8.0.48版本失效了； 临时方案：在47版平板模式登录后，然后升级48可以保留登录，注意备份聊天数据

会被 封号吗

**Comment by xairt** [comment]
在微信开放社区里看到的……

看微信的代码应该是云端根据设备Brand和ABI等信息配置了白名单，微信的LoginSelectUI打开时请求了服务器拉这个配置信息了
![image](https://github.com/rarnu/WeChatPad/assets/28391570/565465b7-fb4c-4b22-8056-45a0e36e18fb)

**Comment by xairt** [comment]
![image](https://github.com/rarnu/WeChatPad/assets/28391570/7c87bace-900e-4b7f-8b2b-3fc958126dc7)

**Comment by zhangliu1988** [comment]
咋解决啊？

**Comment by xueba0458** [comment]
为啥我最新版微信依然有效？？？？？？？？反而用旧版就会提示让我升级

**Comment by mfnag6** [comment]
我拿模拟器试了一下，最新的版本微信（8.0.50，没有嵌入模块），DPI=240的时候都能出现“平板手机同时使用”的选项。在手机上用LsPatch和应用变量改了微信的DPI成为240之后，应用启动界面一开始还是240DPI的效果，但是接下来突然又变成了320DPI。没有出现同时使用的选项。感觉在启动过程中，微信似乎“纠正”了之前强制设定的240DPI。不知道有没有大神能解决这个问题。
![Screenshot_2024-07-05-00-05-01-63_e39d2c7de19156b0683cd93e8735f348](https://github.com/rarnu/WeChatPad/assets/174765025/3b86a965-9006-46b6-859d-57fb1de99a00)
![Screenshot_2024-07-05-00-05-03-94_e39d2c7de19156b0683cd93e8735f348](https://github.com/rarnu/WeChatPad/assets/174765025/442ca59b-ed99-43b0-b4fd-6d6e3157176f)

**Comment by mfnag6** [comment]
解决了吗？请问8.0.48之后的版本怎么办呢？
